### ISSUE TITLE
un-uglify code

### ISSUE THREAD

**Issue by HelloMihai** [MarcelHarabagiu/calc#1]
DRY https://github.com/MarcelHarabagiu/calc/blob/master/script.js#L66-L85

split to separate functions https://github.com/MarcelHarabagiu/calc/blob/master/script.js#L43

**Comment by MarcelHarabagiu** [comment]
DRY was done in https://github.com/MarcelHarabagiu/calc/commit/27721b0d088ae40aa1f568d47fb136604d885ae1 
split functions done in 

1. Equals https://github.com/MarcelHarabagiu/calc/commit/69a50a1b9f2fda226d9e98fc532f93814f739cc8
2. Backspace button https://github.com/MarcelHarabagiu/calc/commit/645783c38e580ab62d12af5953e723df99c34ce9
3. Split clear button function https://github.com/MarcelHarabagiu/calc/commit/5ef94f4b778345fbfa33ea4da0f78af0e23f6deb

**Comment by HelloMihai** [comment]
confirmed working, you can close
